stages:
  - sonar
  - sendmsg

sonar:
  stage:
    sonar
  only:
    - main
  tags:
    - sonar-vm200
  script:
    - echo "$CI_PROJECT_NAME begin scanner"
    - /usr/local/sonar-scanner/bin/sonar-scanner -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.language=go -Dsonar.host.url=http://10.9.68.200:9000/ -Dsonar.login=c82b931d952638dbd809b3199f73f2d1183bc61e

sendmsg:
  stage:
    sendmsg
  only:
    - main
  tags:
    - sonar-vm200
  script:
    - echo $GITLAB_USER_EMAIL
    - echo $CI_PROJECT_NAME
    - echo $CI_COMMIT_REF_NAME
    - |
      /usr/bin/curl --request GET --url http://127.0.0.1:1338/api/v1/sonar/${CI_PROJECT_NAME}/${GITLAB_USER_EMAIL}
